### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by merijn**
* Disable parallel make for mrilu to work around the broken dependencies in it's Makefile
* Switch to using FindMPI instead of hardcoding Trilinos compiler
* Use FindHDF5 to locate libhdf5
* Deduplicate library_dependencies entries
* Fix mrilu C compiler on macOS
* Resolve linker issues on macOS

### CODE REVIEW

**Comment by merijn** [comment]
Ok, so it's broken on Travis because apparently all Trilinos libraries start with "trilinos_" on Ubuntu and not on macOS...

Yay...

**Comment by Sbte** [comment]
Does linking to the utils target fix the unresolved symbols without your

```
    target_link_options(coupledmodel PRIVATE
        LINKER:-U,_outFile,-U,_timer_start_,-U,_timer_stop_)
```

hack?

**Comment by merijn** [comment]
No, I don't actually know where outFile is supposed to come from.

**Comment by Sbte** [comment]
Oh, it seems like there are still 3 variables left that are defined in a header. I'll make an issue for that.

**Comment by merijn** [comment]
Ok, so the linux/Travis setup is somehow slightly different from the Trilinos setup on macOS. It's almost fixed, but it's weekend now so I'll finish it to be ready to merge on monday.

**Comment by erik808** [comment]
Ok. I'll test everything on Cartesius on monday

**Comment by Sbte** [comment]
We should also add OSX compilation to the Travis file to prevent issues like these in the future.

**Pull request merged**
