### PR TITLE
Add macOS Travis tests, simplify Travis matrix setup

### PR DESCRIPTION
**Pull request by merijn**
macOS travis is finally fixed, the transient test still fails, but that's something Sven was looking into.

### CODE REVIEW

**Comment by merijn** [comment]
@Sbte Travis macOS works now if you want to investigate the the failure of the transient test.

**Comment by Sbte** [comment]
I'm looking into this, but I'm still a bit confused by how bad the results are. Maybe the distributions on macOS are actually broken? For this reason I also don't want to fully replace the current distributions by custom ones during tests, because I also want to be able to tell if actual simulations will not produce nonsense (which I can now do by running the tests)...

**Comment by merijn** [comment]
I can help investigate if you tell me what to look for (I didn't really want to reverse engineer all the transient stuff just to figure out where the random numbers come from and what they should be doing :))

**Comment by Sbte** [comment]
It is being used in multiple places. The relevant ones for the tests that fail are

As noise

https://github.com/nlesc-smcm/i-emic/blob/master/src/transient/StochasticThetaModel.H#L55
https://github.com/nlesc-smcm/i-emic/blob/master/src/transient/StochasticProjectedThetaModel.H#L74

To select random trajectories

https://github.com/nlesc-smcm/i-emic/blob/master/src/transient/Transient.hpp#L405
https://github.com/nlesc-smcm/i-emic/blob/master/src/transient/Transient.hpp#L407
https://github.com/nlesc-smcm/i-emic/blob/master/src/transient/Transient.hpp#L734

I computed the actual answers for the problems that I use in the test, which gave the values test against, so that means that the macOS gives wrong answers and linux gives the right answers. It could be related to how I keep reinstantiating the distributions or something, but we may also just be unlucky...

**Comment by merijn** [comment]
Looks like the noise seed of 1 is utterly cursed. I'm playing with different seeds and anything other than 1 passes at least a portion of the ams tests. I'm trying to figure out which seeds will work on both macOS and linux.

**Comment by Sbte** [comment]
It is also fine to adjust the expected values in

https://github.com/nlesc-smcm/i-emic/blob/efa0c2f58282f5adebd4b2af4f41a11ede0c466c/src/tests/test_ams.C#L245-L251

a bit as long as the "Convergence" tests pass.

**Comment by merijn** [comment]
@Sbte I just realised a bigger problem. Those transient tests that are failing on macOS on travis are actually not running *at all* on linux. I was investigating something I broke and I discovered an #if in [Transient.cpp](https://github.com/nlesc-smcm/i-emic/blob/efa0c2f58282f5adebd4b2af4f41a11ede0c466c/src/transient/Transient.cpp#L21) this condition appears to be false (i.e. linux Travis is using a Trilinos that's too old) as shown by this output of me running the test manually/verbosely on Travis: https://travis-ci.com/merijn/i-emic/jobs/221166843#L7914

**Comment by Sbte** [comment]
That is true, but it still runs the Convergence tests. Those pass on linux but did not on macOS. As I said in my previous comment I want those to pass as is, I don't really care about the other ones. They are just there to make sure writing/reading states works.

**Comment by Sbte** [comment]
I wanted to use a "skip" macro for those tests by the way, instead of the `#if`, but that does not yet exist in any release of gtest.

**Comment by merijn** [comment]
I've found a seed that works on both macOS and linux (and some other changes to the install targets, etc. for omuse) which are based upon master, so I'll close this and open a new PR for that branch.

**Pull request closed without merging**
